# Generated by Django 4.2.30 on 2026-06-27 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_notice_grade_behaviorremark_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('class_assigned', models.CharField(blank=True, max_length=100, null=True, verbose_name='Class Assigned (e.g. Class 10-A)')),
                ('total_leaves', models.IntegerField(default=15)),
                ('leaves_taken', models.IntegerField(default=0)),
                ('esic_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ESIC ID')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile_pics/')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='teacher_documents/', verbose_name='Verification Document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
